title: 호곡의 블로그
description: 개발 요모조모.
url: "https://hoogokok.github.io"
theme: minima

collections:
  backend:
    output: true
    permalink: /:collection/:categories/:title/
  frontend:
    output: true
    permalink: /:collection/:categories/:title/
  project:
    output: true
    permalink: /:collection/:categories/:title/

defaults:
  - scope:
      path: ""
      type: "backend"
    values:
      layout: "post"
      collection: "backend"
  - scope:
      path: "_backend/database"
      type: "backend"
    values:
      category: "database"
  - scope:
      path: "_backend/engineering"
      type: "backend"
    values:
      category: "backend_engineering"
  - scope:
      path: ""
      type: "frontend"
    values:
      layout: "post"
      collection: "frontend"
  - scope:
      path: "_frontend/nextjs"
      type: "frontend"
    values:
      category: "nextjs"
  - scope:
      path: "_frontend/frontend_about"
      type: "frontend"
    values:
      category: "frontend_about"
  - scope:
      path: ""
      type: "project"
    values:
      layout: "post"
      collection: "project"
  - scope:
      path: "_project/project"
      type: "project"
    values:
      category: "project_development"

# 카테고리 페이지 생성을 위한 설정
page_gen:
  - data: 'categories'
    template: 'category'
    name: 'category'
    dir: 'categories'
