title: 호곡의 블로그
description: 개발 요모조모.
url: "https://hoogokok.github.io"
theme: minima

collections:
  backend:
    output: true
    permalink: /:collection/:categories/:title/
  frontend:
    output: true
    permalink: /:collection/:categories/:title/
  project:
    output: true
    permalink: /:collection/:categories/:title/


defaults:
  - scope:
      path: ""
      type: "backend"
    values:
      layout: "post"
  - scope:
      path: "_backend/database"
      type: "backend"
    values:
      category: "database"
  - scope:
      path: "_backend/engineering"
      type: "backend"
    values:
      category: "backend_engineering"
  - scope:
      path: ""
      type: "frontend"
    values:
      layout: "post"
  - scope:
      path: "_frontend/next.js"
      type: "frontend"
    values:
      category: "next.js"
  - scope:
      path: "_frontend/frontend_about"
      type: "frontend"
    values:
      category: "frontend_about"
  - scope:
      path: "_project/project_development"
      type: "project"
    values:
      category: "project_development"
